In [1]:
import h5py
import scipy.io
import matplotlib.pyplot as plt
import numpy as np
import pickle
import pandas as pd

In [2]:
matFilename = '../2017-05-12_batchdata_updated_struct_errorcorrect.mat'
f = h5py.File(matFilename)

In [3]:
list(f.keys())

['#refs#', '#subsystem#', 'batch', 'batch_date']

In [4]:
batch = f['batch']

In [5]:
list(batch.keys())

['Vdlin',
 'barcode',
 'channel_id',
 'cycle_life',
 'cycles',
 'policy',
 'policy_readable',
 'summary']

In [6]:
%%time
num_cells = batch['summary'].shape[0]
bat_dict = {}
for i in range(num_cells):
    cl = f[batch['cycle_life'][i,0]].value
    ch_id = f[batch['channel_id'][i,0]].value
    policy = f[batch['policy_readable'][i,0]].value.tobytes()[::2].decode()
    summary_IR = np.hstack(f[batch['summary'][i,0]]['IR'][0,:].tolist())
    summary_QCharge = np.hstack(f[batch['summary'][i,0]]['QCharge'][0,:].tolist())
    summary_QDischarge = np.hstack(f[batch['summary'][i,0]]['QDischarge'][0,:].tolist())
    summary_Tavg = np.hstack(f[batch['summary'][i,0]]['Tavg'][0,:].tolist())
    summary_Tmin = np.hstack(f[batch['summary'][i,0]]['Tmin'][0,:].tolist())
    summary_Tmax = np.hstack(f[batch['summary'][i,0]]['Tmax'][0,:].tolist())
    summary_chargetime = np.hstack(f[batch['summary'][i,0]]['chargetime'][0,:].tolist())
    summary_cycle = np.hstack(f[batch['summary'][i,0]]['cycle'][0,:].tolist())
    summary = {'IR': summary_IR, 'QC': summary_QCharge, 'QD': summary_QDischarge, 'Tavg':
                summary_Tavg, 'Tmin': summary_Tmin, 'Tmax': summary_Tmax, 'chargetime': summary_chargetime,
                'cycle': summary_cycle}
    cycles = f[batch['cycles'][i,0]]
    cycle_dict = {}
#     for j in range(cycles['I'].shape[0]):
#         I = np.hstack((f[cycles['I'][j,0]].value))
#         Qc = np.hstack((f[cycles['Qc'][j,0]].value))
#         Qd = np.hstack((f[cycles['Qd'][j,0]].value))
#         Qdlin = np.hstack((f[cycles['Qdlin'][j,0]].value))
#         T = np.hstack((f[cycles['T'][j,0]].value))
#         Tdlin = np.hstack((f[cycles['Tdlin'][j,0]].value))
#         V = np.hstack((f[cycles['V'][j,0]].value))
#         dQdV = np.hstack((f[cycles['discharge_dQdV'][j,0]].value))
#         t = np.hstack((f[cycles['t'][j,0]].value))
#         cd = {'I': I, 'Qc': Qc, 'Qd': Qd, 'Qdlin': Qdlin, 'T': T, 'Tdlin': Tdlin, 'V':V, 'dQdV': dQdV, 't':t}
#         cycle_dict[str(j)] = cd
        
#     cell_dict = {'cycle_life': cl, 'ch_id':ch_id, 'charge_policy':policy, 'summary': summary, 'cycles': cycle_dict}
    cell_dict = {'cycle_life': cl, 'charge_policy':policy, 'summary': summary}
    key = 'b1c' + str(i)
    bat_dict[key]=   cell_dict

/home/tam/anaconda3/lib/python3.7/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)

CPU times: user 1.01 s, sys: 30 ms, total: 1.04 s
Wall time: 1.1 s

In [7]:
df = pd.DataFrame.from_dict(bat_dict)

In [8]:
df.head()

,b1c0,b1c1,b1c2,b1c3,b1c4,b1c5,b1c6,b1c7,b1c8,b1c9,...,b1c36,b1c37,b1c38,b1c39,b1c40,b1c41,b1c42,b1c43,b1c44,b1c45
cycle_life,[[1190.0]],[[1179.0]],[[1177.0]],[[1226.0]],[[1227.0]],[[1074.0]],[[636.0]],[[870.0]],[[879.0]],[[1054.0]],...,[[704.0]],[[648.0]],[[617.0]],[[625.0]],[[966.0]],[[1051.0]],[[702.0]],[[651.0]],[[616.0]],[[599.0]]
charge_policy,3.6C(80%)-3.6C,3.6C(80%)-3.6C,3.6C(80%)-3.6C,4C(80%)-4C,4C(80%)-4C,4.4C(80%)-4.4C,4.8C(80%)-4.8C,4.8C(80%)-4.8C,5.4C(40%)-3.6C,5.4C(40%)-3.6C,...,7C(40%)-3C,7C(40%)-3C,7C(40%)-3.6C,7C(40%)-3.6C,8C(15%)-3.6C,8C(15%)-3.6C,8C(25%)-3.6C,8C(25%)-3.6C,8C(35%)-3.6C,8C(35%)-3.6C
summary,"{'IR': [0.0, 0.016742354, 0.016724309, 0.01668...","{'IR': [0.0, 0.017038831, 0.017009802, 0.01692...","{'IR': [0.0, 0.01686798, 0.016831938, 0.016718...","{'IR': [0.0, 0.016369704, 0.016315572, 0.01632...","{'IR': [0.0, 0.016787428, 0.016740341, 0.01673...","{'IR': [0.0, 0.016437579, 0.016396422, 0.01636...","{'IR': [0.0, 0.017001977, 0.016977131, 0.01693...","{'IR': [0.0, 0.016311171, 0.016267659, 0.01623...","{'IR': [0.0, 0.016807221, 0.016761683, 0.01674...","{'IR': [0.0, 0.016978227, 0.01692898, 0.016933...",...,"{'IR': [0.0, 0.016480684, 0.016444681, 0.01641...","{'IR': [0.0, 0.016607935, 0.016576257, 0.01654...","{'IR': [0.0, 0.016260354, 0.016216327, 0.01618...","{'IR': [0.0, 0.016743599, 0.016682221, 0.01669...","{'IR': [0.0, 0.016756468, 0.016708069, 0.01670...","{'IR': [0.0, 0.016856873, 0.016819723, 0.01676...","{'IR': [0.0, 0.0167679, 0.016730737, 0.0166876...","{'IR': [0.0, 0.016111452, 0.01610712, 0.016078...","{'IR': [0.0, 0.017436398, 0.017408649, 0.01736...","{'IR': [0.0, 0.016685704, 0.016654616, 0.01661..."

In [9]:
df = df.T
df.head()

,cycle_life,charge_policy,summary
b1c0,[[1190.0]],3.6C(80%)-3.6C,"{'IR': [0.0, 0.016742354, 0.016724309, 0.01668..."
b1c1,[[1179.0]],3.6C(80%)-3.6C,"{'IR': [0.0, 0.017038831, 0.017009802, 0.01692..."
b1c2,[[1177.0]],3.6C(80%)-3.6C,"{'IR': [0.0, 0.01686798, 0.016831938, 0.016718..."
b1c3,[[1226.0]],4C(80%)-4C,"{'IR': [0.0, 0.016369704, 0.016315572, 0.01632..."
b1c4,[[1227.0]],4C(80%)-4C,"{'IR': [0.0, 0.016787428, 0.016740341, 0.01673..."

# Summary

In [10]:
type(df[['summary']])

pandas.core.frame.DataFrame

In [11]:
summary  = df[['summary']]

In [12]:
summary.head()

                                                summary
b1c0  {'IR': [0.0, 0.016742354, 0.016724309, 0.01668...
b1c1  {'IR': [0.0, 0.017038831, 0.017009802, 0.01692...
b1c2  {'IR': [0.0, 0.01686798, 0.016831938, 0.016718...
b1c3  {'IR': [0.0, 0.016369704, 0.016315572, 0.01632...
b1c4  {'IR': [0.0, 0.016787428, 0.016740341, 0.01673...

In [13]:
summary['charge_policy'] = df['charge_policy']

/home/tam/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [14]:
summary.head()

                                                summary   charge_policy
b1c0  {'IR': [0.0, 0.016742354, 0.016724309, 0.01668...  3.6C(80%)-3.6C
b1c1  {'IR': [0.0, 0.017038831, 0.017009802, 0.01692...  3.6C(80%)-3.6C
b1c2  {'IR': [0.0, 0.01686798, 0.016831938, 0.016718...  3.6C(80%)-3.6C
b1c3  {'IR': [0.0, 0.016369704, 0.016315572, 0.01632...      4C(80%)-4C
b1c4  {'IR': [0.0, 0.016787428, 0.016740341, 0.01673...      4C(80%)-4C

In [15]:

df0 = pd.DataFrame()
count = 0
for i, j in summary['summary'].items():
    

    df1 = pd.DataFrame.from_dict(j)
    df1['cell'] = i
    df1['cycle_life'] = df['cycle_life'][i][0][0]  # take the cycle_life from main df and add it in the summary
    df1['C1'] =  float(df['charge_policy'][i].split('C')[0])
    df1['C2'] = float(df['charge_policy'][i].split('-')[-1].split('C')[0])
    df1['Q1'] = int(df['charge_policy'][i].split('(')[1].split(')')[0].split('%')[0])
    
    
    df0 = pd.concat([df0, df1])
       
print(df0.shape)

(38811, 13)

In [16]:
df0.head(10)

,IR,QC,QD,Tavg,Tmin,Tmax,chargetime,cycle,cell,cycle_life,C1,C2,Q1
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,b1c0,1190.0,3.6,3.6,80
1,0.016742,1.071042,1.070689,31.875011,29.566130,35.652016,13.341250,2.0,b1c0,1190.0,3.6,3.6,80
2,0.016724,1.071674,1.071900,31.931490,29.604385,35.692978,13.425777,3.0,b1c0,1190.0,3.6,3.6,80
3,0.016681,1.072304,1.072510,31.932603,29.744202,35.680588,13.425167,4.0,b1c0,1190.0,3.6,3.6,80
4,0.016662,1.072970,1.073174,31.959322,29.644709,35.728691,13.341442,5.0,b1c0,1190.0,3.6,3.6,80
5,0.016623,1.073491,1.073576,31.961062,29.752932,35.711758,13.340835,6.0,b1c0,1190.0,3.6,3.6,80
6,0.016600,1.073922,1.073992,31.900562,29.564377,35.615650,13.340198,7.0,b1c0,1190.0,3.6,3.6,80
7,0.016577,1.074158,1.074374,31.921668,29.628630,35.546783,13.425442,8.0,b1c0,1190.0,3.6,3.6,80
8,0.016588,1.074337,1.074492,31.870082,29.597345,35.539406,13.425190,9.0,b1c0,1190.0,3.6,3.6,80
9,0.016572,1.074353,1.074537,31.841053,29.687315,35.499729,13.425633,10.0,b1c0,1190.0,3.6,3.6,80

In [17]:
df0['Q1'].value_counts()

80    9662
40    8100
50    6847
60    4800
30    3346
15    2015
70    1477
25    1351
35    1213
Name: Q1, dtype: int64

In [18]:
df0.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38811 entries, 0 to 597
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   IR          38811 non-null  float64
 1   QC          38811 non-null  float64
 2   QD          38811 non-null  float64
 3   Tavg        38811 non-null  float64
 4   Tmin        38811 non-null  float64
 5   Tmax        38811 non-null  float64
 6   chargetime  38811 non-null  float64
 7   cycle       38811 non-null  float64
 8   cell        38811 non-null  object
 9   cycle_life  38811 non-null  float64
 10  C1          38811 non-null  float64
 11  C2          38811 non-null  float64
 12  Q1          38811 non-null  int64
dtypes: float64(11), int64(1), object(1)
memory usage: 4.1+ MB

In [19]:
df0['IR'] = df0['IR'].astype('float16')
df0['QC'] = df0['QC'].astype('float16')
df0['QD'] = df0['QD'].astype('float16')
df0['Tavg'] = df0['Tavg'].astype('float16')
df0['Tmin'] = df0['Tmin'].astype('float16')
df0['Tmax'] = df0['Tmax'].astype('float16')
df0['chargetime'] = df0['chargetime'].astype('float16')

df0['cycle_life'] = df0['cycle_life'].astype('int16')

In [20]:
df0.head()

,IR,QC,QD,Tavg,Tmin,Tmax,chargetime,cycle,cell,cycle_life,C1,C2,Q1
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,1.0,b1c0,1190,3.6,3.6,80
1,0.016739,1.071289,1.070312,31.875000,29.562500,35.65625,13.343750,2.0,b1c0,1190,3.6,3.6,80
2,0.016724,1.071289,1.072266,31.937500,29.609375,35.68750,13.421875,3.0,b1c0,1190,3.6,3.6,80
3,0.016678,1.072266,1.072266,31.937500,29.750000,35.68750,13.421875,4.0,b1c0,1190,3.6,3.6,80
4,0.016663,1.073242,1.073242,31.953125,29.640625,35.71875,13.343750,5.0,b1c0,1190,3.6,3.6,80

In [21]:
df0.shape

(38811, 13)

In [22]:
df0.to_pickle('summary_df.pkl')

In [23]:
pd.read_pickle('summary_df.pkl').head()

,IR,QC,QD,Tavg,Tmin,Tmax,chargetime,cycle,cell,cycle_life,C1,C2,Q1
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,1.0,b1c0,1190,3.6,3.6,80
1,0.016739,1.071289,1.070312,31.875000,29.562500,35.65625,13.343750,2.0,b1c0,1190,3.6,3.6,80
2,0.016724,1.071289,1.072266,31.937500,29.609375,35.68750,13.421875,3.0,b1c0,1190,3.6,3.6,80
3,0.016678,1.072266,1.072266,31.937500,29.750000,35.68750,13.421875,4.0,b1c0,1190,3.6,3.6,80
4,0.016663,1.073242,1.073242,31.953125,29.640625,35.71875,13.343750,5.0,b1c0,1190,3.6,3.6,80

In [24]:
df0['Q1'].value_counts()

80    9662
40    8100
50    6847
60    4800
30    3346
15    2015
70    1477
25    1351
35    1213
Name: Q1, dtype: int64

In [25]:
df0.shape

(38811, 13)

In [26]:
df0.columns

Index(['IR', 'QC', 'QD', 'Tavg', 'Tmin', 'Tmax', 'chargetime', 'cycle', 'cell',
       'cycle_life', 'C1', 'C2', 'Q1'],
      dtype='object')